#!/bin/bash

function rmprefix() {
    echo "${1:${#2}}"
}

function aoc() {
    [ $# -lt 1 ] && exit;
    if [ $1 == "deactivate" ]; then
        export PS1=$(rmprefix "$PS1" "$PS1_PREFIX")
        export PS1_PREFIX=

        export REPOROOT=
        unset aoc
    else
        [ $# -lt 1 ] && exit 0
        if [ -e "$REPOROOT/scripts/$1" ]; then
            "$REPOROOT/scripts/$1" ${@:2}
        else
            echo "No such script"
        fi
    fi
}

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
REPOROOT=$(git -C "$SCRIPTPATH" rev-parse --show-toplevel)

if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
    echo "Enabling AoC env.."
    if [ ! -z "$PS1_PREFIX" ]; then
        echo "Already initialized!"
        return 0
    fi
    export PS1_PREFIX="[🎄]:"
    export PS1="$PS1_PREFIX$PS1"

    export REPOROOT="$REPOROOT"
fi
