#!/bin/bash

[ ! -e "$SOLUTIONS_ROOT/cache" ] && mkdir "$SOLUTIONS_ROOT/cache"
zig build-exe --cache-dir "$SOLUTIONS_ROOT/cache" \
    --pkg-begin "console8" "$SOLUTIONS_ROOT/lib/console8.zig" --pkg-end \
    --pkg-begin "aoc" "$SOLUTIONS_ROOT/lib/aoc.zig" --pkg-end \
    main.zig
