#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: prepare <daynum>"
    exit 1
fi

function load() {
    echo -n "$1.."
    $REPOROOT/scripts/scrape ${@:2}
    rv=$?
    if [ $rv -eq 0 ]; then
        echo "done"
    else
        echo "fail"
    fi
    return $rv
}

if [[ "$1" =~ "[0-9]+" ]]; then
    echo "Not a number"
    exit 1
fi

daynum="$1"
folder="$REPOROOT/src/day$daynum"
if [ -e "$folder" ]; then
    echo "Directory for problem already exists"
    exit 1
fi

echo "Initializing folder"

mkdir "$folder"

echo "Copying template"

cp "$REPOROOT/data/template.zig" "$folder/main.zig"

load "Loading problem input" $daynum input
load "Loading first problem text"  $daynum text 1
load "Loading second problem text" $daynum text 1
