#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: prepare <daynum>"
    exit 1
fi

function load() {
    echo -n "$1.."
    $REPOROOT/scripts/scrape ${@:2}
    rv=$?
    if [ $rv -eq 0 ]; then
        echo "done"
    else
        echo "fail"
    fi
    return $rv
}

if [[ "$1" =~ "[0-9]+" ]]; then
    echo "Not a number"
    exit 1
fi

daynum="$1"
folder="$REPOROOT/src/day$daynum"


[ ! -e "$folder" ] && ( echo "Initializing folder"; mkdir "$folder" )
[ ! -e "$folder/main.zig" ] && ( echo "Copying template"; cp "$REPOROOT/data/template.zig" "$folder/main.zig" )

[ ! -e "$folder/input" ] && load "Loading problem input" $daynum input
[ ! -e "$folder/part1" ] && load "Loading first problem text"  $daynum part 1
[ ! -e "$folder/part2" ] && load "Loading second problem text" $daynum part 2
