#!/bin/bash 

[ -z "$REPOROOT" ] && exit 1

[ ! -e "$REPOROOT/cache" ] && mkdir "$REPOROOT/cache"
zig test --cache-dir "$REPOROOT/cache" \
    --pkg-begin "console8" "$REPOROOT/lib/console8.zig" --pkg-end \
    --pkg-begin "aoc" "$REPOROOT/lib/aoc.zig" --pkg-end \
    main.zig
